### ISSUE TITLE
End statement mining offset

### ISSUE THREAD

**Issue by kthoms** [angelozerr/jdt-codemining#39] opened 2018-06-12 10:09 UTC
The end statement is rendered slightly below the line which contains the end statement. The problem gets more visible if you increase the font size.

<img width="1029" alt="screenshot 175" src="https://user-images.githubusercontent.com/265597/41284398-7b28451c-6e39-11e8-9539-d5d8fffe220a.png">

**Comment by angelozerr** [comment] 2018-06-12 16:13
I cannot reproduce in Windows OS:

![image](https://user-images.githubusercontent.com/1932211/41302960-39644f12-6e6c-11e8-9aaf-fa5bbbe2de88.png)

Are you with MacOS? Perhaps it's the same problem than https://github.com/angelozerr/jdt-codemining/issues/14 ?

**Comment by kthoms** [comment] 2018-06-12 18:31
I‘m on Mac. Let‘s have a look together at ECF 😉

**Comment by angelozerr** [comment] 2018-06-12 18:56
> I‘m on Mac. Let‘s have a look together at ECF 

:)

Is https://git.eclipse.org/r/#/c/123367/ fixes your problem?

**Comment by angelozerr** [comment] 2018-06-18 08:28
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=535865

**Comment by angelozerr** [comment] 2018-06-22 10:20
Fixed with https://bugs.eclipse.org/bugs/show_bug.cgi?id=535865

**Closed by angelozerr** 2018-06-22 10:20 UTC
Labels: Platform Bug
